import { CATEGORY_MAP, HEALTHCARE_IDS, RENTAL_IDS, SERVICE_IDS } from './categories'
import type { CategoryId } from './types'

/**
 * What the two horizontal bands say the directory covers.
 *
 * One array per band, and that array is the *only* place the content lives. It
 * is what renders, what the loop is measured from, what gets duplicated to fill
 * the viewport, and what supplies React's keys — see
 * `components/infinite-track.tsx`. There is no parallel "animation list", no
 * desktop/mobile split and no duplicate copy to keep in step. Adding an item
 * here is the whole change; the loop distance, the copy count and the drag all
 * re-derive themselves from the rendered result.
 *
 * The two bands are the same idea at two scales, so they read from the same
 * catalogue in the same order — `CATEGORY_MAP` — and neither hard-codes a name
 * or an emoji.
 */

/**
 * "Covering" — the hero strip. One row, editorial pace.
 *
 * Ordered so the strip alternates between the things people arrive in a hurry
 * for and the things they browse for: an unbroken run of six healthcare
 * categories reads as a healthcare site, which this is not.
 */
export const COVERING_IDS: CategoryId[] = [
  'ambulance',
  'hospital',
  'pharmacy',
  'blood-bank',
  'electrician',
  'plumber',
  'apartment',
  'generator-repair',
  'diagnostic',
  'mechanic',
  'house',
  'doctor',
  'internet',
  'ac-repair',
  'shop',
  'clinic',
  'water-supply',
  'mobile-repair',
]

/**
 * "Everything ELAKAI covers" — the coverage band.
 *
 * One list, not two. The band renders two tracks because two tracks shearing
 * past each other is what makes the section read as *extent* rather than as a
 * carousel, but which item lands in which track is `splitIntoRows`' problem,
 * not the data's. Add a twenty-sixth item and the rows re-balance themselves.
 */
export const COVERS_IDS: CategoryId[] = [
  ...HEALTHCARE_IDS,
  ...SERVICE_IDS,
  ...RENTAL_IDS,
]

/**
 * Which strip a row belongs to. Mirrors the `coverage_band` enum in
 * `supabase/migrations/0003_coverage_bands.sql` — one name for the concept on
 * both sides of the wire.
 */
export type CoverageBandId = 'covering' | 'covers'

export type CoverageBands = Record<CoverageBandId, CategoryId[]>

/** Drop anything the catalogue no longer publishes, and de-duplicate. */
export function cleanCoverage(ids: readonly CategoryId[]): CategoryId[] {
  const seen = new Set<CategoryId>()
  return ids.filter((id) => {
    if (!CATEGORY_MAP[id] || seen.has(id)) return false
    seen.add(id)
    return true
  })
}

/**
 * The bundled answer.
 *
 * Two jobs. It is what the site shows when no backend is configured — a fresh
 * clone, a preview build with no secrets — and it is the seed for
 * `category_bar_items`, generated by `scripts/generate-seed.mjs`. So a
 * connected project starts life agreeing with this file and diverges only
 * where an editor has since changed something.
 *
 * The live read is `loadCoverage()` in `lib/api.ts`, which is where the
 * backend seam belongs; nothing above `api.ts` imports this directly.
 */
export const FALLBACK_COVERAGE: CoverageBands = {
  covering: cleanCoverage(COVERING_IDS),
  covers: cleanCoverage(COVERS_IDS),
}

/**
 * Deal one ordered list into `rows` tracks, keeping the order inside each.
 *
 * Contiguous rather than round-robin, so the editorial grouping of the source
 * list survives: healthcare and the first services stay together on the leading
 * track, the rest and the rentals on the trailing one. Sizes are computed from
 * what is left, so 25 items over 2 rows is 13 and 12 rather than 13 and a
 * remainder — and 1 item over 2 rows is 1 and an empty track, which renders as
 * nothing rather than as a broken strip.
 */
export function splitIntoRows<T>(items: readonly T[], rows: number): T[][] {
  if (rows < 1) return []

  const out: T[][] = []
  let start = 0

  for (let remaining = rows; remaining > 0; remaining--) {
    const take = Math.ceil((items.length - start) / remaining)
    out.push(items.slice(start, start + take))
    start += take
  }

  return out
}
